name: eventepi
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=2.1.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - pip:
    - beautifulsoup4==4.9.0
    - black==19.10b0
    - EpiTator==1.3.5
    - gensim==3.8.3
    - html2text==2020.1.16
    - imbalanced-learn==0.6.2
    - matplotlib==3.2.1
    - nltk==3.5
    - numpy==1.18.3
    - pytest==5.4.1
    - readability-lxml==0.7.1
    - requests==2.23.0
    - scikit-learn==0.23.0
    - translate==3.5.0
    - tqdm==4.45.0
    - click==8.0.1

    